CREATE TABLE T_MYBATIS (
       id NUMBER
     , name VARCHAR2(100)
     , today DATE
);

ALTER TABLE T_MYBATIS ADD CONSTRAINT T_MYBATIS_ID_PK PRIMARY KEY(id);

CREATE SEQUENCE SEQ_MYBATIS;

INSERT INTO T_MYBATIS VALUES (SEQ_MYBATIS.NEXTVAL, 'test', '2022-06-22');

SELECT * FROM T_MYBATIS;
DELETE FROM T_MYBATIS;


SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , HIRE_DATE
     , SALARY
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE 1 = 1
   AND SALARY >= 10000
--   AND HIRE_DATE <= TO_DATE('1995/12/31')
--   AND HIRE_DATE >= TO_DATE('1995/01/01')
   
   AND HIRE_DATE BETWEEN TO_DATE('1990/01/01') AND TO_DATE('2000/12/31')
--   AND DEPARTMENT_ID = 80;
   AND DEPARTMENT_ID IN (80, 90, 100)
  
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , HIRE_DATE
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY >= 10000
 
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , HIRE_DATE
     , SALARY
  FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN TO_DATE('1990/01/01') AND TO_DATE('2000/12/31')
 
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , HIRE_DATE
     , SALARY
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 80;


SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , HIRE_DATE
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY >= 10000
   AND HIRE_DATE BETWEEN TO_DATE('1990/01/01') AND TO_DATE('2000/12/31')
   
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , HIRE_DATE
     , SALARY
  FROM EMPLOYEES
 WHERE SALARY >= 10000
   AND DEPARTMENT_ID = 80;
  
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , HIRE_DATE
     , SALARY
  FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN TO_DATE('1990/01/01') AND TO_DATE('2000/12/31')
   AND DEPARTMENT_ID = 80;



SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;


SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME
     , E.PHONE_NUMBER
     , E.COMMISSION_PCT 
     , E.SALARY
     , D.DEPARTMENT_ID
     , D.DEPARTMENT_NAME
     , J.JOB_ID
     , J.JOB_TITLE
     , J.MIN_SALARY
     , J.MAX_SALARY
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
 WHERE E.EMPLOYEE_ID = 100;

 
 
 
SELECT COUNT(*) AS TOTAL
     , D.DEPARTMENT_NAME AS DEPT_NAME
     , E.DEPARTMENT_ID AS DEPT_CODE
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
-- WHERE E.DEPARTMENT_ID = 80
-- WHERE E.DEPARTMENT_ID IN (80, 90, 100)
-- WHERE E.DEPARTMENT_ID BETWEEN 80 AND 100
 GROUP BY D.DEPARTMENT_NAME, E.DEPARTMENT_ID;
 
 
SELECT * FROM T_MYBATIS;
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 





